// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ0ZbvnsgR85o5Gi7SF1bCzg2cZvUbe_4',
    appId: '1:977840625341:web:acabbdf9af0e62bae849d4',
    messagingSenderId: '977840625341',
    projectId: 'flutter-tools-89d2c',
    authDomain: 'flutter-tools-89d2c.firebaseapp.com',
    storageBucket: 'flutter-tools-89d2c.firebasestorage.app',
    measurementId: 'G-D0P8J6E5QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeVKHXECwnmWprjW-41dOdkgCgzBkX_J0',
    appId: '1:977840625341:android:1ea52cf6fa0a616be849d4',
    messagingSenderId: '977840625341',
    projectId: 'flutter-tools-89d2c',
    storageBucket: 'flutter-tools-89d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnxbMfpgng3HVKDDP4jchN97iVagCgFp0',
    appId: '1:977840625341:ios:7a34018e86a6071de849d4',
    messagingSenderId: '977840625341',
    projectId: 'flutter-tools-89d2c',
    storageBucket: 'flutter-tools-89d2c.firebasestorage.app',
    iosBundleId: 'com.example.tools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnxbMfpgng3HVKDDP4jchN97iVagCgFp0',
    appId: '1:977840625341:ios:7a34018e86a6071de849d4',
    messagingSenderId: '977840625341',
    projectId: 'flutter-tools-89d2c',
    storageBucket: 'flutter-tools-89d2c.firebasestorage.app',
    iosBundleId: 'com.example.tools',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ0ZbvnsgR85o5Gi7SF1bCzg2cZvUbe_4',
    appId: '1:977840625341:web:84be8e38307669b4e849d4',
    messagingSenderId: '977840625341',
    projectId: 'flutter-tools-89d2c',
    authDomain: 'flutter-tools-89d2c.firebaseapp.com',
    storageBucket: 'flutter-tools-89d2c.firebasestorage.app',
    measurementId: 'G-784CWQ75CG',
  );
}
